language: go
go:
  - 1.7
  - 1.8
  - tip
install:
  - go get github.com/Masterminds/glide
  - go get github.com/golang/lint/golint
before_script:
script:
  - go fmt
  - golint .
  - glide install --strip-vendor
  - go build examples/dkrender.go 
  - go test
